<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeCode  = $storeManager->getStore()->getCode();

?>

<div class="contact-details-info">
            <div class="contact-info">
                <div class="contact-title-down">Our Global Offices and Warehouses</div>
            </div>
            <div class="country-1-a <?= ($storeCode === 'us') ? 'activein' : '' ?>">  
            <div class="country-title-1 country-label">United States</div>
            <div class="country-desc <?= ($storeCode === 'us') ? '' : 'inactive' ?>">
            <div class="country-details-1-1-a">
                <span class="country-details-title">Hayward</span>
                <p class="country-details-content">21053 Alexander Ct Unit C,<br> Hayward, CA 94545 USA<br> sales@dcgears.com</p></div>
            <div class="country-details-1-2-a">
                <span class="country-details-title">Virginia</span>
                <p class="country-details-content">Rahi Systems Federal LLC 7760 Doane<br> Dr Building F Historic District,<br> Manassas,VA 20109., USA<br> sales@dcgears.com</p></div>
            <div class="country-details-1-3-a">
                <span class="country-details-title">Reno</span>
                <p class="country-details-content">Rahi Systems Inc 4670<br> Aircenter Circle Reno NV 89502, USA<br> sales@dcgears.com</p></div>
            </div>
            </div>
            <div class="country-2-a <?= ($storeCode === 'in') ? 'activein' : '' ?>">
            <div class="country-title-2 country-label">India</div>
            <div class="country-desc <?= ($storeCode === 'in') ? '' : 'inactive' ?>">
            <div class="country-details-2-1-a">
                <span class="country-details-title">Pune</span>
                <p class="country-details-content">#3 Pride Portal,<br> Shivaji Housing Society,<br> Shivaji Nagar, Pune-411016<br> sales@dcgears.com</p></div>
            <div class="country-details-2-2-a">
                <span class="country-details-title">Mumbai</span>
                <p class="country-details-content">Office no 709,<br> The Summit-Business Bay,<br> Andheri-Kurla Road, Mumbai-400093<br> sales@dcgears.com</p></div>
            <div class="country-details-2-3-a">
                <span class="country-details-title">Bangalore</span>
                <p class="country-details-content">#77, 3rd Cross,<br> 1st Floor Spin Building,<br> Residency Road, Bangalore-560025<br> sales@dcgears.com</p></div>
            </div>
            </div>
            <div class="country-3-a <?= ($storeCode === 'au') ? 'activein' : '' ?>">
            <div class="country-title-3 country-label">Australia</div>
            <div class="country-desc <?= ($storeCode === 'au') ? '' : 'inactive' ?>">
            <div class="country-details-3-1-a">
                <span class="country-details-title">Sydney</span>
                <p class="country-details-content">Unit 30, Slough Business Park,<br> 2 Slough Ave,Silverwater<br> NSW 2128 Australia<br> sales@dcgears.com</p></div>
            <div class="country-details-3-2-a">
                <span class="country-details-title">Melbourne</span>
                <p class="country-details-content">Unit 56/148 Chesterville Rd,<br> Cheltenham VIC 3192<br> sales@dcgears.com</p></div>
            </div>
            </div>
            <div class="country-4-a <?= ($storeCode === 'eu') ? 'activein' : '' ?>">
            <div class="country-title-4 country-label">Europe</div>
            <div class="country-desc <?= ($storeCode === 'eu') ? '' : 'inactive' ?>">
            <div class="country-details-4-1-a">
                <span class="country-details-title">Ireland</span>
                <p class="country-details-content">Rahi Technologies Ltd. Robe House,<br> Cloughkeating Avenue Raheen Business Park, Ireland<br> sales@dcgears.com</p></div>
            <div class="country-details-4-2-a">
                <span class="country-details-title">Netherlands</span>
                <p class="country-details-content">Rahi Jacobus Spijkerdreef <br> Hoofddrorp. The Netherlands 2132PZ<br> sales@dcgears.com</p></div>
            <div class="country-details-4-3-a">
                <span class="country-details-title">Germany</span>
                <p class="country-details-content">Rahi System GmbH, Munchner StraBe<br> 2085774 Unterfohring Munich<br> sales@dcgears.com</p></div>
            </div>
            </div>
            <div class="country-5-a <?= ($storeCode === 'sg') ? 'activein' : '' ?>">
            <div class="country-title-5 country-label">APAC</div>
            <div class="country-desc <?= ($storeCode === 'sg') ? '' : 'inactive' ?>">
            <div class="country-details-5-1-a">
                <span class="country-details-title">Shanghai</span>
                <p class="country-details-content">Shanghai Ruiji Technology Co. Ltd.<br> International Plaza Tower<br> Xuhui, Shanghai, China 200235<br> sales@dcgears.com</p></div>
            <div class="country-details-5-2-a">
                <span class="country-details-title">Beijing</span>
                <p class="country-details-content">Donghuang Building 17th Floor, No.16,<br> South Guangshun Street, Chaoyang District, Beijing, China<br> sales@dcgears.com</p></div>
            <div class="country-details-5-3-a">
                <span class="country-details-title">Singapore</span>
                <p class="country-details-content">Rahi Systems Pte. Ltd.70 Shenton Way, <br>#21-14~15 EON Shenton, Singapore 079118<br> sales@dcgears.com</p></div>
            </div>
            </div>
            <div class="country-6-a <?= ($storeCode === 'uk') ? 'activein' : '' ?>">
            <div class="country-title-6 country-label">UK</div>
            <div class="country-desc <?= ($storeCode === 'uk') ? '' : 'inactive' ?>">
            <div class="country-details-6-1-a">
                <span class="country-details-title"></span>
                <p class="country-details-content"></p></div>
            <div class="country-details-6-2-a">
                <span class="country-details-title">United Kingdom</span>
                <p class="country-details-content">Rahi Systems Limited, One Kingdom Street, <br>London, United Kingdom W2 6BD<br> sales@dcgears.com</p></div>
            <div class="country-details-6-3-a">
                <span class="country-details-title"></span>
                <p class="country-details-content"></p></div>
            </div>
            </div>
            <div class="country-7-a <?= ($storeCode === 'ae') ? 'activein' : '' ?>">
            <div class="country-title-7 country-label">UAE</div>
            <div class="country-desc <?= ($storeCode === 'ae') ? '' : 'inactive' ?>">
            <div class="country-details-7-1-a">
                <span class="country-details-title"></span>
                <p class="country-details-content"></p></div>
            <div class="country-details-7-2-a">
                <span class="country-details-title">Dubai</span>
                <p class="country-details-content">Rahi IT Infrastructure L.L.C. <br>The Citadel Tower, Al Abrej Street, Business Bay,5586, Dubai, UAE<br> sales@dcgears.com</p></div>
            <div class="country-details-7-3-a">
                <span class="country-details-title"></span>
                <p class="country-details-content"></p></div>
            </div>  
            </div>    
        </div>

<style>
span.ttxt {
    font-size: 128%;
    color: #204d93;
    padding: 2px 0px 0px 11px;
}
.combine {
  column-count: 2;
  column-gap: 20px;
}
.contact-paragraph {
  padding: 4%;
  font-size: 13px;
  color: #204d93;
  width: 108%;
}
span.asterisk {
  color: red;
}
hr.new1 {
  border-top: 1px solid #d5e3f1;
  width: 390px;
}
a.text-space {
    padding: 38px;
    font-size: 14px;
}
span.head-title {
    padding: 13px;
    font-size: 18px;
    font-weight: bold;
}
img.img-cat-iconn {
    width: 5%;
}
.contact-infoo {
    margin: -700px 60px 0px 730px;
    height: 203px;
    width: 466px;
}
.country-details-7-1-a {
  width: 280px;
  height: 150px;
  margin: 36px 0px 0px -707px;
  background-color: #fff;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-7-2-a {
  width: 280px;
  height: 150px;
  margin: -150px 0px 0px -528%;
  background-color: #F9f9f9;
  float: left;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-7-3-a {
  width: 280px;
  height: 150px;
  margin: -150px 0px 0px -49px;
  background-color: #fff;
  float: left;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-6-1-a {
  width: 280px;
  height: 150px;
  margin: 36px 0px 0px -707px;
  background-color: #fff;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-6-2-a {
  width: 280px;
  height: 150px;
  margin: -150px 0px 0px -376%;
  background-color: #F9f9f9;
  float: left;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-6-3-a {
  width: 280px;
  height: 150px;
  margin: -150px 0px 0px -49px;
  background-color: #fff;
  float: left;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-5-1-a {
  width: 280px;
  height: 150px;
  margin: 36px 0px 0px -610%;
  background-color: #F9f9f9;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-5-2-a {
  width: 280px;
  height: 150px;
  margin: -150px 0px 0px -223%;
  background-color: #F9f9f9;
  float: left;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-5-3-a {
  width: 280px;
  height: 150px;
  margin: -150px 0px 0px 164%;
  background-color: #F9f9f9;
  float: left;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-4-1-a {
  width: 280px;
  height: 150px;
  margin: 36px 0px 0px -457%;
  background-color: #F9f9f9;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-4-2-a {
  width: 280px;
  height: 150px;
  margin: -150px 0px 0px -70%;
  background-color: #F9f9f9;
  float: left;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-4-3-a {
  width: 280px;
  height: 150px;
  margin: -150px 0px 0px 318%;
  background-color: #F9f9f9;
  float: left;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-3-1-a {
  width: 280px;
  height: 150px;
  margin: 36px 0px 0px -149%;
  background-color: #F9f9f9;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-3-2-a {
  width: 280px;
  height: 150px;
  margin: -150px 0px 0px 312%;
  background-color: #F9f9f9;
  float: left;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-2-1-a {
  width: 280px;
  height: 150px;
  margin: 36px 0px 0px -154%;
  background-color: #F9f9f9;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-2-2-a {
  width: 280px;
  height: 150px;
  margin: -150px 0px 0px 232%;
  background-color: #F9f9f9;
  float: left;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-2-3-a {
  width: 280px;
  height: 150px;
  margin: -150px 0px 0px 623%;
  background-color: #F9f9f9;
  float: left;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center; 
}
p.country-details-content {
    color: #2a4a7d;
    text-align: center;
    font-size: 15px;
    padding: 10px;
}
span.country-details-title {
    font-size: 20px;
    font-weight: 800;
    color: #2a4a7d;
    margin: 10px;
}
.country-details-1-1-a {
  width: 280px;
  height: 150px;
  margin: 36px 0px 0px 0%;
  background-color: #F9f9f9;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-1-2-a {
  width: 280px;
  height: 150px;
  margin: -150px 0px 0px 387%;
  background-color: #F9f9f9;
  float: left;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.country-details-1-3-a {
  width: 280px;
  height: 150px;
  margin: -150px 0px 0px 774%;
  background-color: #F9f9f9;
  float: left;
  box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
  border-radius: 11.2373px;
  text-align: center;
  display: grid;
  align-items: center;
}
.inactive {
    display: none;
}
.activein {
    background-color: #d5e3f1;
}
.country-1-a {
  width: 10%;
  height: 41px;
  border-radius: 7px;
  border: solid 1px #d5e3f1;
  margin: 0px 0px 0px 0%;
}
.country-2-a {
  width: 10%;
  height: 41px;
  margin: -41px 0px 0px 15%;
  border-radius: 7px;
  border: solid 1px #d5e3f1;
}
.country-3-a {
  width: 10%;
  height: 41px;
  margin: -41px 0px 0px 30%;
  border-radius: 7px;
  border: solid 1px #d5e3f1;
}
.country-4-a {
  width: 10%;
  height: 41px;
  margin: -41px 0px 0px 45%;
  border-radius: 7px;
  border: solid 1px #d5e3f1;
}
.country-5-a {
  width: 10%;
  height: 41px;
  margin: -41px 0px 0px 60%;
  border-radius: 7px;
  border: solid 1px #d5e3f1;
}
.country-6-a {
  width: 10%;
  height: 41px;
  margin: -41px 0px 0px 75%;
  border-radius: 7px;
  border: solid 1px #d5e3f1;
}
.country-7-a {
  width: 10%;
  height: 41px;
  margin: -41px 0px 0px 90%;
  border-radius: 7px;
  border: solid 1px #d5e3f1;
}
.country-title-1 {
    font-size: 18px;
    margin: 6px 0px 0px 4%;
    color: #2a4a7d;
}
.country-title-2 {
    font-size: 18px;
    margin: 6px 0px 0px 31%;
    color: #2a4a7d;
}
.country-title-3 {
    font-size: 18px;
    margin: 6px 0px 0px 20%;
    color: #2a4a7d;
}
.country-title-4 {
    font-size: 18px;
    margin: 6px 0px 0px 26%;
    color: #2a4a7d;
}
.country-title-5 {
    font-size: 18px;
    margin: 6px 0px 0px 29%;
    color: #2a4a7d;
}
.country-title-6 {
    font-size: 18px;
    margin: 6px 0px 0px 39%;
    color: #2a4a7d;
}
.country-title-7 {
    font-size: 18px;
    margin: 6px 0px 0px 33%;
    color: #2a4a7d;
}
.coll-google-map {
    padding: 123px 0px 0px 155px;
}
.vll {
    border-left: 1px solid #d5e3f1;
    height: 620px;
    float: left;
    margin: 85px 0px 0px -625px;
}
.contact-title-top {
    margin: 15px;
    color: #204d93;
}
span.txt {
    margin: 16px;
    font-size: 128%;
    color: #204d93;
}
.contact-info {
    text-align: center;
    color: #2a4a7d;
    padding: 20px 0px 20px 0px;
}
.contact-title-down {
    font-size: 27px;
    font-weight: bold;
}
p.contact-title-down-paragraph {
    font-size: 17px;
}
@media(max-width: 768px){
.contact-info {
    padding: 0px !important;
}
.contact-infoo {
    margin: 9px 0px 0px 5px !important;
    height: 245px !important;
    width: 348px !important;
}
.country-1-a {
    width: 50.5px !important;
    margin: 0px 0px 0px -3%;
}
.country-details-1-1-a {
    margin: 36px 0px 0px 108%;
}
.country-details-1-2-a {
    margin: 11px 0px 0px 110%;
}
.country-details-1-3-a {
    margin: 12px 0px 0px 114%;
}
.country-2-a {
    width: 50.5px !important;
    margin: -41px 0px 0px 12%;
}
.country-details-2-1-a {
    margin: 36px 0px 0px -8%;
}
.country-details-2-2-a {
    margin: 11px 0px 0px -8%;
}
.country-details-2-3-a {
    margin: 12px 0px 0px -8%;
}
.coll-google-map {
    padding: 16px 225px 0px 0px !important
}
.country-3-a {
    width: 50.5px !important;
    margin: -41px 0px 0px 27%;
}
.country-details-3-1-a {
    margin: 27px 0px 0px -123%;
}
.country-details-3-2-a {
    margin: 15px 0px 0px -123%;
}
.country-4-a {
    width: 50.5px !important;
    margin: -41px 0px 0px 42%;
}
.country-details-4-1-a {
    margin: 20px 0px 0px -234%;
}
.country-details-4-2-a {
    margin: 11px 0px 0px -234%;
}
.country-details-4-3-a {
    margin: 11px 0px 0px -234%;
}
.country-5-a {
    width: 50.5px !important;
    margin: -41px 0px 0px 57%;
}
.country-details-5-1-a {
    margin: 20px 0px 0px -348%;
}
.country-details-5-2-a {
    margin: 11px 0px 0px -348%;
}
.country-details-5-3-a {
    margin: 11px 0px 0px -348%;
}
.country-6-a {
    width: 50.5px !important;
    margin: -41px 0px 0px 72%;
}
.country-details-6-1-a {
    margin: 28px 0px 0px -219px !important;
}
.country-details-6-2-a {
    margin: -154px 0px 0px -471%;
}
.country-details-6-3-a {
    display: none !important;
}
.country-7-a {
    width: 50.5px !important;
    margin: -41px 0px 0px 87%;
}
.country-details-7-1-a {
    margin: 26px 0px 0px 1px !important;
}
.country-details-7-2-a {
    margin: -154px 0px 0px -582%;
}
.country-details-7-3-a {
    display: none !important;
}
.country-title-1 {
   font-size: 11px !important;
   margin: 0px 0px 0px 6px !important;
}
.country-title-2 {
    font-size: 11px !important;
    margin: 0px 0px 0px 11px !important;
    padding: 9px 0px 0px 0px !important;
}
.country-title-3 {
    font-size: 10px !important;
    margin: 0px 0px 0px 3px !important;
    padding: 10px 0px 0px 0px !important;
}
.country-title-4 {
    font-size: 11px !important;
    margin: 0px 0px 0px 5px !important;
    padding: 9px 0px 0px 0px !important;
}
.country-title-5 {
    font-size: 11px !important;
    margin: 0px 0px 0px 11px !important;
    padding: 10px 0px 0px 0px !important;
}
.country-title-6 {
    font-size: 11px !important;
    margin: 0px 0px 0px 3px !important;
    padding: 10px 0px 0px 13px !important;
}
.country-title-7 {
    font-size: 11px !important;
    margin: 0px 0px 0px 15px !important;
    padding: 10px 0px 0px 0px !important;
}
.contact-us-page {
    margin: 0px 0px 10px -24px !important;
}
}
</style>
<script>
require(['jquery'], function($){
    $(document).ready(function(){
        $('.country-label').click(function(){
            $(".country-label").parent().removeClass("activein"); 
            $(".country-label").siblings('.country-desc').addClass("inactive"); 
            $(this).siblings('.country-desc').removeClass("inactive");
            $(this).parent().addClass("activein");
        });
    });
});
</script>

