<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeCode  = $storeManager->getStore()->getCode();

?>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script>
    require(['jquery'], function($) {
        $(document).ready(function() {
            var setCountry;
            $('#formsubmit').on('click', function() {
                var code = $("#Countryphone").val();
                setCountry = countryCodeToCountry(code);
                $("#Country").val(setCountry);
                var getURL = window.location;
                $("input[name='LEADCF8']").val(getURL).change();
            });

            function countryCodeToCountry(code) {
                if (code == "1") return "USA";
                if (code == "44") return "UK";
                if (code == "213") return "Algeria";
                if (code == "376") return "Andorra";
                if (code == "244") return "Angola";
                if (code == "1264") return "Anguilla";
                if (code == "1268") return "Antigua &amp; Barbuda";
                if (code == "54") return "Argentina";
                if (code == "374") return "Armenia";
                if (code == "297") return "Aruba";
                if (code == "61") return "Australia";
                if (code == "43") return "Austria";
                if (code == "994") return "Azerbaijan";
                if (code == "1242") return "Bahamas";
                if (code == "973") return "Bahrain";
                if (code == "880") return "Bangladesh";
                if (code == "1246") return "Barbados";
                if (code == "375") return "Belarus";
                if (code == "32") return "Belgium";
                if (code == "501") return "Belize";
                if (code == "229") return "Benin";
                if (code == "1441") return "Bermuda";
                if (code == "975") return "Bhutan";
                if (code == "591") return "Bolivia";
                if (code == "387") return "Bosnia Herzegovina";
                if (code == "267") return "Botswana";
                if (code == "55") return "Brazil";
                if (code == "673") return "Brunei";
                if (code == "359") return "Bulgaria";
                if (code == "226") return "Burkina Faso";
                if (code == "257") return "Burundi";
                if (code == "855") return "Cambodia";
                if (code == "237") return "Cameroon";
                if (code == "1") return "Canada";
                if (code == "238") return "Cape Verde Islands";
                if (code == "1345") return "Cayman Islands";
                if (code == "236") return "Central African Republic";
                if (code == "56") return "Chile";
                if (code == "86") return "China";
                if (code == "57") return "Colombia";
                if (code == "269") return "Comoros";
                if (code == "242") return "Congo";
                if (code == "682") return "Cook Islands";
                if (code == "506") return "Costa Rica";
                if (code == "385") return "Croatia";
                if (code == "53") return "Cuba";
                if (code == "90392") return "Cyprus North";
                if (code == "357") return "Cyprus South";
                if (code == "42") return "Czech Republic";
                if (code == "45") return "Denmark";
                if (code == "253") return "Djibouti";
                if (code == "1809") return "Dominica";
                if (code == "1809") return "Dominican Republic";
                if (code == "593") return "Ecuador";
                if (code == "20") return "Egypt";
                if (code == "503") return "El Salvador";
                if (code == "240") return "Equatorial Guinea";
                if (code == "291") return "Eritrea";
                if (code == "372") return "Estonia";
                if (code == "251") return "Ethiopia";
                if (code == "500") return "Falkland Islands";
                if (code == "298") return "Faroe Islands";
                if (code == "679") return "Fiji";
                if (code == "358") return "Finland";
                if (code == "33") return "France";
                if (code == "594") return "French Guiana";
                if (code == "689") return "French Polynesia";
                if (code == "241") return "Gabon";
                if (code == "220") return "Gambia";
                if (code == "7880") return "Georgia";
                if (code == "49") return "Germany";
                if (code == "233") return "Ghana";
                if (code == "350") return "Gibraltar";
                if (code == "30") return "Greece";
                if (code == "299") return "Greenland";
                if (code == "147") return "Grenada";
                if (code == "590") return "Guadeloupe";
                if (code == "671") return "Guam";
                if (code == "502") return "Guatemala";
                if (code == "224") return "Guinea";
                if (code == "245") return "Guinea - Bissau";
                if (code == "592") return "Guyana";
                if (code == "509") return "Haiti";
                if (code == "504") return "Honduras";
                if (code == "852") return "Hong Kong";
                if (code == "36") return "Hungary";
                if (code == "354") return "Iceland";
                if (code == "91") return "India";
                if (code == "62") return "Indonesia";
                if (code == "98") return "Iran";
                if (code == "964") return "Iraq";
                if (code == "353") return "Ireland";
                if (code == "972") return "Israel";
                if (code == "39") return "Italy";
                if (code == "1876") return "Jamaica";
                if (code == "81") return "Japan";
                if (code == "962") return "Jordan";
                if (code == "7") return "Kazakhstan";
                if (code == "254") return "Kenya";
                if (code == "686") return "Kiribati";
                if (code == "850") return "Korea North";
                if (code == "82") return "Korea South";
                if (code == "965") return "Kuwait";
                if (code == "996") return "Kyrgyzstan";
                if (code == "856") return "Laos";
                if (code == "371") return "Latvia";
                if (code == "961") return "Lebanon";
                if (code == "266") return "Lesotho";
                if (code == "231") return "Liberia";
                if (code == "218") return "Libya";
                if (code == "417") return "Liechtenstein";
                if (code == "370") return "Lithuania";
                if (code == "352") return "Luxembourg";
                if (code == "853") return "Macao";
                if (code == "389") return "Macedonia";
                if (code == "261") return "Madagascar";
                if (code == "265") return "Malawi";
                if (code == "60") return "Malaysia";
                if (code == "960") return "Maldives";
                if (code == "223") return "Mali";
                if (code == "356") return "Malta";
                if (code == "692") return "Marshall Islands";
                if (code == "596") return "Martinique";
                if (code == "222") return "Mauritania";
                if (code == "269") return "Mayotte";
                if (code == "52") return "Mexico";
                if (code == "691") return "Micronesia";
                if (code == "373") return "Moldova";
                if (code == "377") return "Monaco";
                if (code == "976") return "Mongolia";
                if (code == "1664") return "Montserrat";
                if (code == "212") return "Morocco";
                if (code == "258") return "Mozambique";
                if (code == "95") return "Myanmar";
                if (code == "264") return "Namibia";
                if (code == "674") return "Nauru";
                if (code == "977") return "Nepal";
                if (code == "31") return "Netherlands";
                if (code == "687") return "New Caledonia";
                if (code == "64") return "New Zealand";
                if (code == "505") return "Nicaragua";
                if (code == "227") return "Niger";
                if (code == "234") return "Nigeria";
                if (code == "683") return "Niue";
                if (code == "672") return "Norfolk Islands";
                if (code == "670") return "Northern Marianas";
                if (code == "47") return "Norway";
                if (code == "968") return "Oman";
                if (code == "680") return "Palau";
                if (code == "507") return "Panama";
                if (code == "675") return "Papua New Guinea";
                if (code == "595") return "Paraguay";
                if (code == "51") return "Peru";
                if (code == "63") return "Philippines";
                if (code == "48") return "Poland";
                if (code == "351") return "Portugal";
                if (code == "1787") return "Puerto Rico";
                if (code == "974") return "Qatar";
                if (code == "262") return "Reunion";
                if (code == "40") return "Romania";
                if (code == "7") return "Russia";
                if (code == "250") return "Rwanda";
                if (code == "378") return "San Marino";
                if (code == "239") return "Sao Tome &amp; Principe";
                if (code == "966") return "Saudi Arabia";
                if (code == "221") return "Senegal";
                if (code == "381") return "Serbia";
                if (code == "248") return "Seychelles";
                if (code == "232") return "Sierra Leone";
                if (code == "65") return "Singapore";
                if (code == "421") return "Slovak Republic";
                if (code == "386") return "Slovenia";
                if (code == "677") return "Solomon Islands";
                if (code == "252") return "Somalia";
                if (code == "27") return "South Africa";
                if (code == "34") return "Spain";
                if (code == "94") return "Sri Lanka";
                if (code == "290") return "St. Helena";
                if (code == "1869") return "St. Kitts";
                if (code == "1758") return "St. Lucia";
                if (code == "249") return "Sudan";
                if (code == "597") return "Suriname";
                if (code == "268") return "Swaziland";
                if (code == "46") return "Sweden";
                if (code == "41") return "Switzerland";
                if (code == "963") return "Syria";
                if (code == "886") return "Taiwan";
                if (code == "7") return "Tajikstan";
                if (code == "66") return "Thailand";
                if (code == "228") return "Togo";
                if (code == "676") return "Tonga";
                if (code == "1868") return "Trinidad &amp; Tobago";
                if (code == "216") return "Tunisia";
                if (code == "90") return "Turkey";
                if (code == "993") return "Turkmenistan";
                if (code == "1649") return "Turks &amp; Caicos Islands";
                if (code == "688") return "Tuvalu";
                if (code == "256") return "Uganda";
                if (code == "44") return "UK";
                if (code == "380") return "Ukraine";
                if (code == "971") return "United Arab Emirates";
                if (code == "598") return "Uruguay";
                if (code == "1") return "USA";
                if (code == "7") return "Uzbekistan";
                if (code == "678") return "Vanuatu";
                if (code == "379") return "Vatican City";
                if (code == "58") return "Venezuela";
                if (code == "84") return "Vietnam";
                if (code == "1284") return "Virgin Islands - British";
                if (code == "1340") return "Virgin Islands - US";
                if (code == "681") return "Wallis &amp; Futuna";
                if (code == "969") return "Yemen (North)";
                if (code == "967") return "Yemen (South)";
                if (code == "260") return "Zambia";
                if (code == "263") return "Zimbabwe";
                return '';
            };

        })
    });
</script>

<div class="contact-us-page row">
    <div class="col-lg-5 col-md-5 col-sm-5 contactus-form-right">
        <div class="contact-title-top">
            <h2>Let's Talk</h2>
        </div>
        <div class="contact-paragraph">To request a quote or to ask for a free demo and infrastructure assessment fill out the form and our DC expert will get back to you in no time with a perfectly tailored solution for your requirement.</div>
        <div class="contactus">
            <form action='https://crm.zoho.in/crm/WebToLeadForm' name=WebToLeads329181000000257001 method='POST' onSubmit='javascript:document.charset="UTF-8"; return checkMandatory329181000000257001()' accept-charset='UTF-8'>
                <input type='text' style='display:none;' name='xnQsjsdp' value='6cd952f3e5be67584d0644fe79b8ff8fea78abdc9f436bd23b83e47605cabebd'></input>
                <input type='hidden' name='zc_gad' id='zc_gad' value=''></input>
                <input type='text' style='display:none;' name='xmIwtLD' value='11d2381a628d4e940a5dcf2b3cf079bacdbef2105b8a2867d53fa4a03cc6ccb3'></input>
                <input type='text' style='display:none;' name='actionType' value='TGVhZHM='></input>
                <input type='text' style='display:none;' name='returnURL' value='http&#x3a;&#x2f;&#x2f;dcgears.com/thank-you&#x2f;'></input>
                <!-- Do not remove this code. -->
                <input type='text' style='display:none;' id='ldeskuid' name='ldeskuid'></input>
                <input type='text' style='display:none;' id='LDTuvid' name='LDTuvid'></input>
                <!-- Do not remove this code. -->
                <input type='text' style='display:none;' id='Lead_Source' name='Lead Source' value="Online&#x20;Store"></input>
                <input type='text' style='display:none;' id='LEADCF8' name='LEADCF8' value=""></input>



                <div class="form-field">
                    <label><span class="txt">Your Name<span class="asterisk">*</span></span></label>
                    <input style="border-radius: 4px;   margin: 8px 15.3px 9px 13.5px;
                        padding: 6px 233px 6px 10px;" type="text" name="Last Name" id="Last_Name" placeholder="Ex. John Doe" required />
                </div>

                <div class="form-field">
                    <label><span class="txt">Company Email<span class="asterisk">*</span></span></label>
                    <input style="border-radius: 4px;   margin: 8px 15.3px 9px 13.5px;" type="email" name="Email" id="Email" placeholder="Ex. john.doe@example.com" required />
                </div>
        </div>
        <div class="form-field row">
            <div class="col-md-4">
                <label><span class="ttxt">Contact No<span class="asterisk">*</span></span></label>
                <select style="border-radius: 4px; color: #666; margin: 6px 3px -4px 15px; padding: 0px 0px 0px 3px;" id="Countryphone" name="Countryphone" placeholder="Country.." required />
                <option value='' selected=''>Country Code</option>
                <option Country="US" value="1">USA (+1)</option>
                <option country="GB" value="44">UK (+44)</option>
                <option Country="DZ" value="213">Algeria (+213)</option>
                <option Country="AD" value="376">Andorra (+376)</option>
                <option Country="AO" value="244">Angola (+244)</option>
                <option Country="AI" value="1264">Anguilla (+1264)</option>
                <option Country="AG" value="1268">Antigua &amp; Barbuda (+1268)</option>
                <option Country="AR" value="54">Argentina (+54)</option>
                <option Country="AM" value="374">Armenia (+374)</option>
                <option Country="AW" value="297">Aruba (+297)</option>
                <option Country="AU" value="61">Australia (+61)</option>
                <option Country="AT" value="43">Austria (+43)</option>
                <option Country="AZ" value="994">Azerbaijan (+994)</option>
                <option Country="BS" value="1242">Bahamas (+1242)</option>
                <option Country="BH" value="973">Bahrain (+973)</option>
                <option Country="BD" value="880">Bangladesh (+880)</option>
                <option Country="BB" value="1246">Barbados (+1246)</option>
                <option Country="BY" value="375">Belarus (+375)</option>
                <option Country="BE" value="32">Belgium (+32)</option>
                <option Country="BZ" value="501">Belize (+501)</option>
                <option Country="BJ" value="229">Benin (+229)</option>
                <option Country="BM" value="1441">Bermuda (+1441)</option>
                <option Country="BT" value="975">Bhutan (+975)</option>
                <option Country="BO" value="591">Bolivia (+591)</option>
                <option Country="BA" value="387">Bosnia Herzegovina (+387)</option>
                <option Country="BW" value="267">Botswana (+267)</option>
                <option Country="BR" value="55">Brazil (+55)</option>
                <option Country="BN" value="673">Brunei (+673)</option>
                <option Country="BG" value="359">Bulgaria (+359)</option>
                <option Country="BF" value="226">Burkina Faso (+226)</option>
                <option Country="BI" value="257">Burundi (+257)</option>
                <option Country="KH" value="855">Cambodia (+855)</option>
                <option Country="CM" value="237">Cameroon (+237)</option>
                <option Country="CA" value="1">Canada (+1)</option>
                <option Country="CV" value="238">Cape Verde Islands (+238)</option>
                <option Country="KY" value="1345">Cayman Islands (+1345)</option>
                <option Country="CF" value="236">Central African Republic (+236)</option>
                <option Country="CL" value="56">Chile (+56)</option>
                <option Country="CN" value="86">China (+86)</option>
                <option Country="CO" value="57">Colombia (+57)</option>
                <option Country="KM" value="269">Comoros (+269)</option>
                <option Country="CG" value="242">Congo (+242)</option>
                <option Country="CK" value="682">Cook Islands (+682)</option>
                <option Country="CR" value="506">Costa Rica (+506)</option>
                <option Country="HR" value="385">Croatia (+385)</option>
                <option Country="CU" value="53">Cuba (+53)</option>
                <option Country="CY" value="90392">Cyprus North (+90392)</option>
                <option Country="CY" value="357">Cyprus South (+357)</option>
                <option Country="CZ" value="42">Czech Republic (+42)</option>
                <option Country="DK" value="45">Denmark (+45)</option>
                <option Country="DJ" value="253">Djibouti (+253)</option>
                <option Country="DM" value="1809">Dominica (+1809)</option>
                <option Country="DO" value="1809">Dominican Republic (+1809)</option>
                <option Country="EC" value="593">Ecuador (+593)</option>
                <option Country="EG" value="20">Egypt (+20)</option>
                <option Country="SV" value="503">El Salvador (+503)</option>
                <option Country="GQ" value="240">Equatorial Guinea (+240)</option>
                <option Country="ER" value="291">Eritrea (+291)</option>
                <option Country="EE" value="372">Estonia (+372)</option>
                <option Country="ET" value="251">Ethiopia (+251)</option>
                <option Country="FK" value="500">Falkland Islands (+500)</option>
                <option Country="FO" value="298">Faroe Islands (+298)</option>
                <option Country="FJ" value="679">Fiji (+679)</option>
                <option Country="FI" value="358">Finland (+358)</option>
                <option Country="FR" value="33">France (+33)</option>
                <option Country="GF" value="594">French Guiana (+594)</option>
                <option Country="PF" value="689">French Polynesia (+689)</option>
                <option Country="GA" value="241">Gabon (+241)</option>
                <option Country="GM" value="220">Gambia (+220)</option>
                <option Country="GE" value="7880">Georgia (+7880)</option>
                <option Country="DE" value="49">Germany (+49)</option>
                <option Country="GH" value="233">Ghana (+233)</option>
                <option Country="GI" value="350">Gibraltar (+350)</option>
                <option Country="GR" value="30">Greece (+30)</option>
                <option Country="GL" value="299">Greenland (+299)</option>
                <option Country="GD" value="1473">Grenada (+1473)</option>
                <option Country="GP" value="590">Guadeloupe (+590)</option>
                <option Country="GU" value="671">Guam (+671)</option>
                <option Country="GT" value="502">Guatemala (+502)</option>
                <option Country="GN" value="224">Guinea (+224)</option>
                <option Country="GW" value="245">Guinea - Bissau (+245)</option>
                <option Country="GY" value="592">Guyana (+592)</option>
                <option Country="HT" value="509">Haiti (+509)</option>
                <option Country="HN" value="504">Honduras (+504)</option>
                <option Country="HK" value="852">Hong Kong (+852)</option>
                <option Country="HU" value="36">Hungary (+36)</option>
                <option Country="IS" value="354">Iceland (+354)</option>
                <option Country="IN" value="91">India (+91)</option>
                <option Country="ID" value="62">Indonesia (+62)</option>
                <option Country="IR" value="98">Iran (+98)</option>
                <option Country="IQ" value="964">Iraq (+964)</option>
                <option Country="IE" value="353">Ireland (+353)</option>
                <option Country="IL" value="972">Israel (+972)</option>
                <option Country="IT" value="39">Italy (+39)</option>
                <option Country="JM" value="1876">Jamaica (+1876)</option>
                <option Country="JP" value="81">Japan (+81)</option>
                <option Country="JO" value="962">Jordan (+962)</option>
                <option Country="KZ" value="7">Kazakhstan (+7)</option>
                <option Country="KE" value="254">Kenya (+254)</option>
                <option Country="KI" value="686">Kiribati (+686)</option>
                <option Country="KP" value="850">Korea North (+850)</option>
                <option Country="KR" value="82">Korea South (+82)</option>
                <option Country="KW" value="965">Kuwait (+965)</option>
                <option Country="KG" value="996">Kyrgyzstan (+996)</option>
                <option Country="LA" value="856">Laos (+856)</option>
                <option Country="LV" value="371">Latvia (+371)</option>
                <option Country="LB" value="961">Lebanon (+961)</option>
                <option Country="LS" value="266">Lesotho (+266)</option>
                <option Country="LR" value="231">Liberia (+231)</option>
                <option Country="LY" value="218">Libya (+218)</option>
                <option Country="LI" value="417">Liechtenstein (+417)</option>
                <option Country="LT" value="370">Lithuania (+370)</option>
                <option Country="LU" value="352">Luxembourg (+352)</option>
                <option Country="MO" value="853">Macao (+853)</option>
                <option Country="MK" value="389">Macedonia (+389)</option>
                <option Country="MG" value="261">Madagascar (+261)</option>
                <option Country="MW" value="265">Malawi (+265)</option>
                <option Country="MY" value="60">Malaysia (+60)</option>
                <option Country="MV" value="960">Maldives (+960)</option>
                <option Country="ML" value="223">Mali (+223)</option>
                <option Country="MT" value="356">Malta (+356)</option>
                <option Country="MH" value="692">Marshall Islands (+692)</option>
                <option Country="MQ" value="596">Martinique (+596)</option>
                <option Country="MR" value="222">Mauritania (+222)</option>
                <option Country="YT" value="269">Mayotte (+269)</option>
                <option Country="MX" value="52">Mexico (+52)</option>
                <option Country="FM" value="691">Micronesia (+691)</option>
                <option Country="MD" value="373">Moldova (+373)</option>
                <option Country="MC" value="377">Monaco (+377)</option>
                <option Country="MN" value="976">Mongolia (+976)</option>
                <option Country="MS" value="1664">Montserrat (+1664)</option>
                <option Country="MA" value="212">Morocco (+212)</option>
                <option Country="MZ" value="258">Mozambique (+258)</option>
                <option Country="MN" value="95">Myanmar (+95)</option>
                <option Country="NA" value="264">Namibia (+264)</option>
                <option Country="NR" value="674">Nauru (+674)</option>
                <option Country="NP" value="977">Nepal (+977)</option>
                <option Country="NL" value="31">Netherlands (+31)</option>
                <option Country="NC" value="687">New Caledonia (+687)</option>
                <option Country="NZ" value="64">New Zealand (+64)</option>
                <option Country="NI" value="505">Nicaragua (+505)</option>
                <option Country="NE" value="227">Niger (+227)</option>
                <option Country="NG" value="234">Nigeria (+234)</option>
                <option Country="NU" value="683">Niue (+683)</option>
                <option Country="NF" value="672">Norfolk Islands (+672)</option>
                <option Country="NP" value="670">Northern Marianas (+670)</option>
                <option Country="NO" value="47">Norway (+47)</option>
                <option Country="OM" value="968">Oman (+968)</option>
                <option Country="PW" value="680">Palau (+680)</option>
                <option Country="PA" value="507">Panama (+507)</option>
                <option Country="PG" value="675">Papua New Guinea (+675)</option>
                <option Country="PY" value="595">Paraguay (+595)</option>
                <option Country="PE" value="51">Peru (+51)</option>
                <option Country="PH" value="63">Philippines (+63)</option>
                <option Country="PL" value="48">Poland (+48)</option>
                <option Country="PT" value="351">Portugal (+351)</option>
                <option Country="PR" value="1787">Puerto Rico (+1787)</option>
                <option Country="QA" value="974">Qatar (+974)</option>
                <option Country="RE" value="262">Reunion (+262)</option>
                <option Country="RO" value="40">Romania (+40)</option>
                <option Country="RU" value="7">Russia (+7)</option>
                <option Country="RW" value="250">Rwanda (+250)</option>
                <option Country="SM" value="378">San Marino (+378)</option>
                <option Country="ST" value="239">Sao Tome &amp; Principe (+239)</option>
                <option Country="SA" value="966">Saudi Arabia (+966)</option>
                <option Country="SN" value="221">Senegal (+221)</option>
                <option Country="CS" value="381">Serbia (+381)</option>
                <option Country="SC" value="248">Seychelles (+248)</option>
                <option Country="SL" value="232">Sierra Leone (+232)</option>
                <option Country="SG" value="65">Singapore (+65)</option>
                <option Country="SK" value="421">Slovak Republic (+421)</option>
                <option Country="SI" value="386">Slovenia (+386)</option>
                <option Country="SB" value="677">Solomon Islands (+677)</option>
                <option Country="SO" value="252">Somalia (+252)</option>
                <option Country="ZA" value="27">South Africa (+27)</option>
                <option Country="ES" value="34">Spain (+34)</option>
                <option Country="LK" value="94">Sri Lanka (+94)</option>
                <option Country="SH" value="290">St. Helena (+290)</option>
                <option Country="KN" value="1869">St. Kitts (+1869)</option>
                <option Country="SC" value="1758">St. Lucia (+1758)</option>
                <option Country="SD" value="249">Sudan (+249)</option>
                <option Country="SR" value="597">Suriname (+597)</option>
                <option Country="SZ" value="268">Swaziland (+268)</option>
                <option Country="SE" value="46">Sweden (+46)</option>
                <option Country="CH" value="41">Switzerland (+41)</option>
                <option Country="SI" value="963">Syria (+963)</option>
                <option Country="TW" value="886">Taiwan (+886)</option>
                <option Country="TJ" value="7">Tajikstan (+7)</option>
                <option Country="TH" value="66">Thailand (+66)</option>
                <option Country="TG" value="228">Togo (+228)</option>
                <option Country="TO" value="676">Tonga (+676)</option>
                <option Country="TT" value="1868">Trinidad &amp; Tobago (+1868)</option>
                <option Country="TN" value="216">Tunisia (+216)</option>
                <option Country="TR" value="90">Turkey (+90)</option>
                <option Country="TM" value="7">Turkmenistan (+7)</option>
                <option Country="TM" value="993">Turkmenistan (+993)</option>
                <option Country="TC" value="1649">Turks &amp; Caicos Islands (+1649)</option>
                <option Country="TV" value="688">Tuvalu (+688)</option>
                <option Country="UG" value="256">Uganda (+256)</option>
                <option Country="GB" value="44">UK (+44)</option>
                <option Country="UA" value="380">Ukraine (+380)</option>
                <option Country="AE" value="971">United Arab Emirates (+971)</option>
                <option Country="UY" value="598">Uruguay (+598)</option>
                <option Country="US" value="1">USA (+1)</option>
                <option Country="UZ" value="7">Uzbekistan (+7)</option>
                <option Country="VU" value="678">Vanuatu (+678)</option>
                <option Country="VA" value="379">Vatican City (+379)</option>
                <option Country="VE" value="58">Venezuela (+58)</option>
                <option Country="VN" value="84">Vietnam (+84)</option>
                <option Country="VG" value="84">Virgin Islands - British (+1284)</option>
                <option Country="VI" value="84">Virgin Islands - US (+1340)</option>
                <option Country="WF" value="681">Wallis &amp; Futuna (+681)</option>
                <option Country="YE" value="969">Yemen (North)(+969)</option>
                <option Country="YE" value="967">Yemen (South)(+967)</option>
                <option Country="ZM" value="260">Zambia (+260)</option>
                <option Country="ZW" value="263">Zimbabwe (+263)</option>
                </select>
            </div>
            <div class="col-md-8">
                <input style="border-radius: 4px; margin: 30px 0px 6px 13px;" type='tel' name='Phone' id="Phone" placeholder="1234567890" required />
            </div>
        </div>
        <div class="form-field">
            <label><span class="txt">Message / Requirement<span class="asterisk">*</span></span></label>
            <textarea style="margin: 7px 0px 12px 13.5px; border-radius: 4px;" rows="5" name="Description" id="Description" placeholder="Write your message here" required /></textarea>
              <div class="g-recaptcha" data-sitekey="6LdrupcgAAAAABhk7e_sUb-0YEqznpMbfC-VVl2m"></div>
        </div>
        <input type='hidden' name='Country' id='Country' value=''></input>
        <input style="margin: 0% 0% 0% 41%; padding: 12.5px 36.5px 11px; border-radius: 3px; background: #e08222; border: antiquewhite;" class="button btn btn-primary btn-lg" id="formsubmit" type="submit" value="Submit" />
        <div class='zcwf_col_fld'>
            <script>
                function validateEmail329181000000257001() {
                    var form = document.forms['WebToLeads329181000000257001'];
                    var emailFld = form.querySelectorAll('[ftype=email]');
                    var i;
                    for (i = 0; i < emailFld.length; i++) {
                        var emailVal = emailFld[i].value;
                        if ((emailVal.replace(/^\s+|\s+$/g, '')).length != 0) {
                            var atpos = emailVal.indexOf('@');
                            var dotpos = emailVal.lastIndexOf('.');
                            if (atpos < 1 || dotpos < atpos + 2 || dotpos + 2 >= emailVal.length) {
                                alert('Please enter a valid email address. ');
                                emailFld[i].focus();
                                return false;
                            }
                        }
                    }
                    return true;
                }

                function checkMandatory329181000000257001() {
                    var mndFileds = new Array('Last Name', 'Email');
                    var fldLangVal = new Array('Your\x20Name', 'Company\x20Email');
                    for (i = 0; i < mndFileds.length; i++) {
                        var fieldObj = document.forms['WebToLeads329181000000257001'][mndFileds[i]];
                        if (fieldObj) {
                            if (((fieldObj.value).replace(/^\s+|\s+$/g, '')).length == 0) {
                                if (fieldObj.type == 'file') {
                                    alert('Please select a file to upload.');
                                    fieldObj.focus();
                                    return false;
                                }
                                alert(fldLangVal[i] + ' cannot be empty.');
                                fieldObj.focus();
                                return false;
                            } else if (fieldObj.nodeName == 'SELECT') {
                                if (fieldObj.options[fieldObj.selectedIndex].value == '-None-') {
                                    alert(fldLangVal[i] + ' cannot be none.');
                                    fieldObj.focus();
                                    return false;
                                }
                            } else if (fieldObj.type == 'checkbox') {
                                if (fieldObj.checked == false) {
                                    alert('Please accept  ' + fldLangVal[i]);
                                    fieldObj.focus();
                                    return false;
                                }
                            }
                            try {
                                if (fieldObj.name == 'Last Name') {
                                    name = fieldObj.value;
                                }
                            } catch (e) {}
                        }
                    }
                    trackVisitor329181000000257001();
                    if (!validateEmail329181000000257001()) {
                        return false;
                    }
                    document.querySelector('.crmWebToEntityForm .formsubmit').setAttribute('disabled', true);
                }

                function tooltipShow329181000000257001(el) {
                    var tooltip = el.nextElementSibling;
                    var tooltipDisplay = tooltip.style.display;
                    if (tooltipDisplay == 'none') {
                        var allTooltip = document.getElementsByClassName('zcwf_tooltip_over');
                        for (i = 0; i < allTooltip.length; i++) {
                            allTooltip[i].style.display = 'none';
                        }
                        tooltip.style.display = 'block';
                    } else {
                        tooltip.style.display = 'none';
                    }
                }
            </script>
            <script type='text/javascript' id='VisitorTracking'>
                var $zoho = $zoho || {};
                $zoho.salesiq = $zoho.salesiq || {
                    widgetcode: '5df7e7831b236fcc065778ecb30ce63a842ed86f15ff1ace3e8f57da0ca4bedc',
                    values: {},
                    ready: function() {}
                };
                var d = document;
                s = d.createElement('script');
                s.type = 'text/javascript';
                s.id = 'zsiqscript';
                s.defer = true;
                s.src = 'https://salesiq.zoho.in/widget';
                t = d.getElementsByTagName('script')[0];
                t.parentNode.insertBefore(s, t);

                function trackVisitor329181000000257001() {
                    try {
                        if ($zoho) {
                            var LDTuvidObj = document.forms['WebToLeads329181000000257001']['LDTuvid'];
                            if (LDTuvidObj) {
                                LDTuvidObj.value = $zoho.salesiq.visitor.uniqueid();
                            }
                            var firstnameObj = document.forms['WebToLeads329181000000257001']['First Name'];
                            if (firstnameObj) {
                                name = firstnameObj.value + ' ' + name;
                            }
                            $zoho.salesiq.visitor.name(name);
                            var emailObj = document.forms['WebToLeads329181000000257001']['Email'];
                            if (emailObj) {
                                email = emailObj.value;
                                $zoho.salesiq.visitor.email(email);
                            }
                        }
                    } catch (e) {}
                }
            </script>
            <!-- Do not remove this --- Analytics Tracking code starts -->
            <script id='wf_anal' src='https://crm.zohopublic.in/crm/WebFormAnalyticsServeServlet?rid=11d2381a628d4e940a5dcf2b3cf079bacdbef2105b8a2867d53fa4a03cc6ccb3gid6cd952f3e5be67584d0644fe79b8ff8fea78abdc9f436bd23b83e47605cabebdgid534cb20477b1d28b5f45f7cc241888c5gid4ee3a7e9ace6ab1be7c541b329164307&tw=096a715cbfc30dc79d6dc215bf71c5b4284d938378e51186a6daa9337f7519a8'></script>
            <!-- Do not remove this --- Analytics Tracking code ends. -->
        </div>
        </form>
    </div>

    <div class="col-lg-1 col-md-1 col-sm-1 contactus-from-middle vll"></div>

    <div class="col-lg-5 col-md-5 col-sm-5 contactus-form-left">
        <div class="coll-google-map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12666.802810438945!2d-121.935913!3d37.467788!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd83756cd0350509!2sRahi%20Systems%20Inc%20-%20Global%20IT%20Solutions%20Provider!5e0!3m2!1sen!2sus!4v1648096353055!5m2!1sen!2sus" width="108%" height="300" frameborder="0" allowfullscreen=""></iframe>
        </div>
        <div class="contact-infoo">
            <div class="contact-content">
                <ul class="address-info">
                    <li class="add-icon"><img src="https://dev.dcgears.com/media/catalog/menu_icon/kvm_switches/Headquarters.svg" class="img-cat-iconn" alt=""><span class="head-title">Headquarter</span></li><a class="text-space">Rahi Systems Inc. 48303 Fremont Blvd,
                        CA 94538 USA</a>
                    <hr class="new1">
                    <li class="img-cat-iconn"><img src="https://dev.dcgears.com/media/catalog/menu_icon/kvm_switches/Email.svg" class="img-cat-iconn" alt=""><span class="head-title">Email Address</span></li><a class="text-space" title="Send Email" href="mailto:sales@dcgears.com">sales@dcgears.com</a>
                    <hr class="new1">
                    <li class="img-cat-iconn"><img src="https://dev.dcgears.com/media/catalog/menu_icon/kvm_switches/Call_information.svg" class="img-cat-iconn" alt=""><span class="head-title">Call Information</span></li><a class="text-space" title="Call" href="tel:(+1) 510 651 2205">(+1) 510 651 2205</a>
                </ul>
            </div>
        </div>
    </div>
</div>

</div>

<div class="contact-details-info">
    <div class="contact-info">
        <div class="contact-title-down">Our offices around the globe</div>
        <p class="contact-title-down-paragraph">With offices and warehouses in more than 33 countries and physical presence in 40+ locations DC Gears have the ability to deliver IT solutions across the globe.</p>
    </div>
    <div class="country-1 <?= ($storeCode === 'us') ? 'active' : '' ?>">
        <div class="country-title-1 country-label">United States</div>
        <div class="country-desc <?= ($storeCode === 'us') ? '' : 'inactive' ?>">
            <div class="country-details-1-1">
                <span class="country-details-title">Hayward</span>
                <p class="country-details-content">21053 Alexander Ct Unit C,<br> Hayward, CA 94545 USA<br> sales@dcgears.com</p>
            </div>
            <div class="country-details-1-2">
                <span class="country-details-title">Virginia</span>
                <p class="country-details-content">Rahi Systems Federal LLC 7760 Doane<br> Dr Building F Historic District,<br> Manassas,VA 20109., USA<br> sales@dcgears.com</p>
            </div>
            <div class="country-details-1-3">
                <span class="country-details-title">Reno</span>
                <p class="country-details-content">Rahi Systems Inc 4670<br> Aircenter Circle Reno NV 89502, USA<br> sales@dcgears.com</p>
            </div>
        </div>
    </div>
    <div class="country-2 <?= ($storeCode === 'in') ? 'active' : '' ?>">
        <div class="country-title-2 country-label">India</div>
        <div class="country-desc <?= ($storeCode === 'in') ? '' : 'inactive' ?>">
            <div class="country-details-2-1">
                <span class="country-details-title">Pune</span>
                <p class="country-details-content">#3 Pride Portal,<br> Shivaji Housing Society,<br> Shivaji Nagar, Pune-411016<br> sales@dcgears.com</p>
            </div>
            <div class="country-details-2-2">
                <span class="country-details-title">Mumbai</span>
                <p class="country-details-content">Office no 709,<br> The Summit-Business Bay,<br> Andheri-Kurla Road, Mumbai-400093<br> sales@dcgears.com</p>
            </div>
            <div class="country-details-2-3">
                <span class="country-details-title">Bangalore</span>
                <p class="country-details-content">#77, 3rd Cross,<br> 1st Floor Spin Building,<br> Residency Road, Bangalore-560025<br> sales@dcgears.com</p>
            </div>
        </div>
    </div>
    <div class="country-3 <?= ($storeCode === 'au') ? 'active' : '' ?>">
        <div class="country-title-3 country-label">Australia</div>
        <div class="country-desc <?= ($storeCode === 'au') ? '' : 'inactive' ?>">
            <div class="country-details-3-1">
                <span class="country-details-title">Sydney</span>
                <p class="country-details-content">Unit 30, Slough Business Park,<br> 2 Slough Ave,Silverwater<br> NSW 2128 Australia<br> sales@dcgears.com</p>
            </div>
            <div class="country-details-3-2">
                <span class="country-details-title">Melbourne</span>
                <p class="country-details-content">Unit 56/148 Chesterville Rd,<br> Cheltenham VIC 3192<br> sales@dcgears.com</p>
            </div>
        </div>
    </div>
    <div class="country-4 <?= ($storeCode === 'eu') ? 'active' : '' ?>">
        <div class="country-title-4 country-label">Europe</div>
        <div class="country-desc <?= ($storeCode === 'eu') ? '' : 'inactive' ?>">
            <div class="country-details-4-1">
                <span class="country-details-title">Ireland</span>
                <p class="country-details-content">Rahi Technologies Ltd. Robe House,<br> Cloughkeating Avenue Raheen Business Park, Ireland<br> sales@dcgears.com</p>
            </div>
            <div class="country-details-4-2">
                <span class="country-details-title">Netherlands</span>
                <p class="country-details-content">Rahi Jacobus Spijkerdreef <br> Hoofddrorp. The Netherlands 2132PZ<br> sales@dcgears.com</p>
            </div>
            <div class="country-details-4-3">
                <span class="country-details-title">Germany</span>
                <p class="country-details-content">Rahi Systems GmbH<br> London, Münchner Straße 2085774 Unterföhring Munich<br> sales@dcgears.com</p>
            </div>
        </div>
    </div>
    <div class="country-5 <?= ($storeCode === 'sg') ? 'active' : '' ?>">
        <div class="country-title-5 country-label">APAC</div>
        <div class="country-desc <?= ($storeCode === 'sg') ? '' : 'inactive' ?>">
            <div class="country-details-5-1">
                <span class="country-details-title">Shanghai</span>
                <p class="country-details-content">Shanghai Ruiji Technology Co. Ltd.<br> International Plaza Tower<br> Xuhui, Shanghai, China 200235<br> sales@dcgears.com</p>
            </div>
            <div class="country-details-5-2">
                <span class="country-details-title">Beijing</span>
                <p class="country-details-content">Donghuang Building 17th Floor, No.16,<br> South Guangshun Street, Chaoyang District, Beijing, China<br> sales@dcgears.com</p>
            </div>
            <div class="country-details-5-3">
                <span class="country-details-title">Singapore</span>
                <p class="country-details-content">Rahi Systems Pte. Ltd.<br> 70 Shenton Way, <br> #21-14~15 EON Shenton,
                    Singapore <br> sales@dcgears.com</p>
            </div>
        </div>
    </div>
    <div class="country-6 <?= ($storeCode === 'uk') ? 'active' : '' ?>">
        <div class="country-title-6 country-label">UK</div>
        <div class="country-desc <?= ($storeCode === 'uk') ? '' : 'inactive' ?>">
            <div class="country-details-6-1">
                <span class="country-details-title"></span>
                <p class="country-details-content"></p>
            </div>
            <div class="country-details-6-2">
                <span class="country-details-title">United Kingdom</span>
                <p class="country-details-content">Rahi Systems Limited, One Kingdom Street, <br>London, United Kingdom W2 6BD<br> sales@dcgears.com</p>
            </div>
            <div class="country-details-6-3">
                <span class="country-details-title"></span>
                <p class="country-details-content"></p>
            </div>
        </div>
    </div>
    <div class="country-7 <?= ($storeCode === 'ae') ? 'active' : '' ?>">
        <div class="country-title-7 country-label">UAE</div>
        <div class="country-desc <?= ($storeCode === 'ae') ? '' : 'inactive' ?>">
            <div class="country-details-7-1">
                <span class="country-details-title"></span>
                <p class="country-details-content"></p>
            </div>
            <div class="country-details-7-2">
                <span class="country-details-title">Dubai</span>
                <p class="country-details-content">Rahi IT Infrastructure L.L.C. <br>The Citadel Tower, Al Abrej Street, Business Bay,5586, Dubai, UAE<br> sales@dcgears.com</p>
            </div>
            <div class="country-details-7-3">
                <span class="country-details-title"></span>
                <p class="country-details-content"></p>
            </div>
        </div>
    </div>
</div>
</div>
<style>
    .g-recaptcha {
    margin: 0px 0px 9px 13px;
    }

    .col-lg-5.col-md-5.col-sm-5.contactus-form-left {
        margin: 0px 0px 0px -60px;
    }

    span.ttxt {
        font-size: 128%;
        color: #204d93;
        padding: 0px 0px 0px 16px;
    }

    .combine {
        column-count: 2;
        column-gap: 20px;
    }

    .contact-paragraph {
        padding: 3%;
        font-size: 13px;
        color: #204d93;
        width: 108%;
    }

    span.asterisk {
        color: red;
    }

    hr.new1 {
        border-top: 1px solid #d5e3f1;
        width: 390px;
    }

    a.text-space {
        padding: 38px;
        font-size: 14px;
    }

    span.head-title {
        padding: 13px;
        font-size: 18px;
        font-weight: bold;
    }

    img.img-cat-iconn {
        width: 5%;
    }

    .contact-infoo {
        margin: 17px 60px 0px 0px;
        height: 203px;
        width: 466px;
    }

    .country-details-7-1 {
        width: 280px;
        height: 150px;
        margin: 36px 0px 0px -707px;
        background-color: #fff;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-7-2 {
        width: 280px;
        height: 150px;
        margin: -150px 0px 0px -525%;
        background-color: #F9f9f9;
        float: left;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-7-3 {
        width: 280px;
        height: 150px;
        margin: -150px 0px 0px -49px;
        background-color: #fff;
        float: left;
        text-align: center;
        display: grid;
        align-items: center;
    }

    .country-details-6-1 {
        width: 280px;
        height: 150px;
        margin: 36px 0px 0px -707px;
        background-color: #fff;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-6-2 {
        width: 280px;
        height: 150px;
        margin: -150px 0px 0px -373%;
        background-color: #F9f9f9;
        float: left;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-6-3 {
        width: 280px;
        height: 150px;
        margin: -150px 0px 0px -49px;
        background-color: #fff;
        float: left;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-5-1 {
        width: 280px;
        height: 150px;
        margin: 36px 0px 0px -591%;
        background-color: #F9f9f9;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-5-2 {
        width: 280px;
        height: 150px;
        margin: -150px 0px 0px -220%;
        background-color: #F9f9f9;
        float: left;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-5-3 {
        width: 280px;
        height: 150px;
        margin: -150px 0px 0px 163%;
        background-color: #F9f9f9;
        float: left;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        display: grid;
        align-items: center;
	text-align: center;
    }

    .country-details-4-1 {
        width: 280px;
        height: 150px;
        margin: 36px 0px 0px -438%;
        background-color: #F9f9f9;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-4-2 {
        width: 280px;
        height: 150px;
        margin: -150px 0px 0px -68%;
        background-color: #F9f9f9;
        float: left;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-4-3 {
        width: 280px;
        height: 150px;
        margin: -150px 0px 0px 315%;
        background-color: #F9f9f9;
        float: left;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-3-1 {
        width: 280px;
        height: 150px;
        margin: 36px 0px 0px -149%;
        background-color: #F9f9f9;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-3-2 {
        width: 280px;
        height: 150px;
        margin: -150px 0px 0px 300%;
        background-color: #F9f9f9;
        float: left;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-2-1 {
        width: 280px;
        height: 150px;
        margin: 36px 0px 0px -143%;
        background-color: #F9f9f9;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-2-2 {
        width: 280px;
        height: 150px;
        margin: -150px 0px 0px 228%;
        background-color: #F9f9f9;
        float: left;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-2-3 {
        width: 280px;
        height: 150px;
        margin: -150px 0px 0px 612%;
        background-color: #F9f9f9;
        float: left;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
	display: grid;
        align-items: center;
    }

    p.country-details-content {
        color: #2a4a7d;
        text-align: center;
        font-size: 15px;
        padding: 10px;
    }

    span.country-details-title {
        font-size: 20px;
        font-weight: 800;
        color: #2a4a7d;
        margin: 10px;
    }

    .country-details-1-1 {
        width: 280px;
        height: 150px;
        margin: 36px 0px 0px 0%;
        background-color: #F9f9f9;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
	display: grid;
        align-items: center;
    }

    .country-details-1-2 {
        width: 280px;
        height: 150px;
        margin: -150px 0px 0px 375%;
        background-color: #F9f9f9;
        float: left;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
        display: grid;
        align-items: center;
    }

    .country-details-1-3 {
        width: 280px;
        height: 150px;
        margin: -150px 0px 0px 754%;
        background-color: #F9f9f9;
        float: left;
        box-shadow: 0px 2.99662px 2.99662px rgb(0 0 0 / 8%);
        border-radius: 11.2373px;
        text-align: center;
 	display: grid;
        align-items: center;
    }

    .inactive {
        display: none;
    }

    .active {
        background-color: #d5e3f1;
    }

    .country-1 {
        width: 10%;
        height: 41px;
        border-radius: 7px;
        border: solid 1px #d5e3f1;
	margin: 0px 0px 0px 1%;
    }

    .country-2 {
        width: 10%;
        height: 41px;
        margin: -41px 0px 0px 15%;
        border-radius: 7px;
        border: solid 1px #d5e3f1;
    }

    .country-3 {
        width: 10%;
        height: 41px;
        margin: -41px 0px 0px 30%;
        border-radius: 7px;
        border: solid 1px #d5e3f1;
    }

    .country-4 {
        width: 10%;
        height: 41px;
        margin: -41px 0px 0px 44%;
        border-radius: 7px;
        border: solid 1px #d5e3f1;
    }

    .country-5 {
        width: 10%;
        height: 41px;
        margin: -41px 0px 0px 59%;
        border-radius: 7px;
        border: solid 1px #d5e3f1;
    }

    .country-6 {
        width: 10%;
        height: 41px;
        margin: -41px 0px 0px 74%;
        border-radius: 7px;
        border: solid 1px #d5e3f1;
    }

    .country-7 {
        width: 10%;
        height: 41px;
        margin: -41px 0px 0px 89%;
        border-radius: 7px;
        border: solid 1px #d5e3f1;
    }

    .country-title-1 {
        font-size: 18px;
        margin: 5px 0px 0px 3px;
        color: #2a4a7d;
    }

    .country-title-2 {
        font-size: 18px;
        margin: 5px 0px 0px 35px;
        color: #2a4a7d;
    }

    .country-title-3 {
        font-size: 18px;
        margin: 5px 0px 0px 23px;
        color: #2a4a7d;
    }

    .country-title-4 {
        font-size: 18px;
        margin: 5px 0px 0px 30px;
        color: #2a4a7d;
    }

    .country-title-5 {
        font-size: 18px;
        margin: 5px 0px 0px 32px;
        color: #2a4a7d;
    }

    .country-title-6 {
        font-size: 18px;
        margin: 5px 0px 0px 43px;
        color: #2a4a7d;
    }

    .country-title-7 {
        font-size: 18px;
        margin: 5px 0px 0px 41px;
        color: #2a4a7d;
    }

    .coll-google-map {
        padding: 79px 0px 0px 0px;
    }

    .col-lg-4.col-md-40 {
        margin: 0px 0px 0px 114px;
    }

    .vll {
        border-left: 1px solid #d5e3f1;
        height: 620px;
        margin: 0px 0px 0px 60px;
    }

    .contact-title-top {
        margin: 15px;
        color: #204d93;
    }

    span.txt {
        margin: 16px;
        font-size: 128%;
        color: #204d93;
    }

    .contact-info {
        text-align: center;
        color: #2a4a7d;
        padding: 50px;
    }

    .contact-title-down {
        font-size: 27px;
        font-weight: bold;
    }

    p.contact-title-down-paragraph {
        font-size: 17px;
    }

    @media only screen and (min-device-width : 320px) and (max-device-width : 480px){
        .contact-info {
            padding: 0px !important;
        }

        .contact-infoo {
            margin: 9px 0px 0px 5px !important;
            height: 245px !important;
            width: 348px !important;
        }

        .country-1 {
            width: 50.5px !important;
            margin: 0px 0px 0px -3% !important;
        }

        .country-details-1-1 {
            margin: 51% 0% 0% 108% !important;
        }

        .country-details-1-2 {
            margin: 56% 0% 0% 108% !important;
        }

        .country-details-1-3 {
            margin: 56% 0% 0% 108% !important;
        }

        .country-2 {
            width: 50.5px !important;
            margin: -41px 0px 0px 12% !important;
        }

        .country-details-2-1 {
            margin: 60% 0% 0% -8% !important;
        }

        .country-details-2-2 {
            margin: 60% 0% 0% -8% !important;
        }

        .country-details-2-3 {
            margin: 60% 0% 0% -8% !important;
        }

        .coll-google-map {
            padding: 0px 0px 0px 0px !important
        }

        .country-3 {
            width: 50.5px !important;
            margin: -41px 0px 0px 27% !important;
        }

        .country-details-3-1 {
            margin: 56% 0% 0% -121% !important;
        }

        .country-details-3-2 {
            margin: 56% 0% 0% -121% !important;
        }

        .country-4 {
            width: 50.5px !important;
            margin: -41px 0px 0px 42% !important;
        }

        .country-details-4-1 {
            margin: 56% 0% 0% -230% !important;
        }

        .country-details-4-2 {
            margin: 56% 0% 0% -230% !important;
        }

        .country-details-4-3 {
            margin: 56% 0% 0% -230% !important;
        }

        .country-5 {
            width: 50.5px !important;
            margin: -41px 0px 0px 57% !important;
        }

        .country-details-5-1 {
            margin: 56% 0% 0% -353% !important;
        }

        .country-details-5-2 {
            margin: 56% 0% 0% -353% !important;
        }

        .country-details-5-3 {
            margin: 56% 0% 0% -353% !important;
        }

        .country-6 {
            width: 50.5px !important;
            margin: -41px 0px 0px 72% !important;
        }

        .country-details-6-2 {
            margin: -311% 0% 0% -467% !important;
        }

        .country-details-6-3 {
            display: none !important;
        }

        .country-7 {
            width: 50.5px !important;
            margin: -41px 0px 0px 87% !important;
        }

        .country-details-7-2 {
            margin: -314% 0% 0% -580% !important;
        }

        .country-details-7-3 {
            display: none !important;
        }

        .country-title-1 {
            font-size: 11px !important;
            margin: 0px 0px 0px 6px !important;
        }

        .country-title-2 {
            font-size: 11px !important;
            margin: 0px 0px 0px 11px !important;
            padding: 9px 0px 0px 0px !important;
        }

        .country-title-3 {
            font-size: 10px !important;
            margin: 0px 0px 0px 3px !important;
            padding: 10px 0px 0px 0px !important;
        }

        .country-title-4 {
            font-size: 11px !important;
            margin: 0px 0px 0px 5px !important;
            padding: 9px 0px 0px 0px !important;
        }

        .country-title-5 {
            font-size: 11px !important;
            margin: 0px 0px 0px 11px !important;
            padding: 10px 0px 0px 0px !important;
        }

        .country-title-6 {
            font-size: 11px !important;
            margin: 0px 0px 0px 3px !important;
            padding: 10px 0px 0px 13px !important;
        }

        .country-title-7 {
            font-size: 11px !important;
            margin: 0px 0px 0px 15px !important;
            padding: 10px 0px 0px 0px !important;
        }

        .contact-us-page {
            margin: 0px 0px 10px -24px !important;
        }

        .col-lg-1.col-md-1.col-sm-1.contactus-from-middle.vll {
            display: none;
        }

        .col-lg-5.col-md-5.col-sm-5.contactus-form-left {
            margin: 10px 0px 0px -3px !important;
        }
    }
    @media only screen and (min-device-width : 768px) and (max-device-width : 1024px){
        .country-title-1.country-label {
            font-size: 13px !important;
            margin: -1px 0px 0px 26px !important;
        }
        .country-title-2.country-label {
            font-size: 17px !important;
            margin: 7px 0px 0px 28px !important;
        }
        .country-title-3.country-label {
            font-size: 15px !important;
            margin: 8px 0px 0px 15px !important;
        }
        .country-title-4.country-label {
            font-size: 16px !important;
            margin: 7px 0px 0px 20px !important;
        }
        .country-title-5.country-label {
            font-size: 17px !important;
            margin: 7px 0px 0px 23px !important;
        }
        .country-title-6.country-label {
            font-size: 17px !important;
            margin: 7px 0px 0px 34px !important;
        }
        .country-title-7.country-label {
            font-size: 17px !important;
            margin: 7px 0px 0px 29px !important;
        }
	.country-details-1-2 {
            margin: -150px 0px 0px 345%;
        }
        .country-details-1-3 {
            margin: -150px 0px 0px 696%;
        }
	.country-details-2-2 {
            margin: -150px 0px 0px 205%;
        }
	.country-details-2-3 {
            margin: -150px 0px 0px 553%;
        }
   	.country-details-3-1 {
            margin: 36px 0px 0px -155%;
        }
	.country-details-3-2 {
 	    margin: -150px 0px 0px 247%;
        }
	.country-details-4-2 {
            margin: -150px 0px 0px -92%;
        }
	.country-details-4-3 {
            margin: -150px 0px 0px 258%;
        }
        .country-details-5-2 {
            margin: -150px 0px 0px -244%;
        }
	.country-details-5-3 {
            margin: -150px 0px 0px 105%;
        }
	.country-details-6-2 {
            margin: -150px 0px 0px -406%;
        }
	.country-details-7-2 {
            margin: -150px 0px 0px -555%;
        }
    }
</style>
<script>
    require(['jquery'], function($) {
        $(document).ready(function() {
            $('.country-label').click(function() {
                $(".country-label").parent().removeClass("active");
                $(".country-label").siblings('.country-desc').addClass("inactive");
                $(this).siblings('.country-desc').removeClass("inactive");
                $(this).parent().addClass("active");
            });
        });
    });
</script>
